import React from 'react'
import { Box } from '@material-ui/core'
import * as I from '@material-ui/icons'
import AudioButton from '../Audiobutton'

const Audioplayer = () => (
	<Box>
		<AudioButton
			backgroundColor="#4A148C"
			icon={I.Eco}
			src="https://actions.google.com/sounds/v1/ambiences/carnival_atmosphere.ogg"
		/>
		<AudioButton
			backgroundColor="#BF360C"
			icon={I.Explore}
			src="https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg"
		/>
		<AudioButton
			backgroundColor="#004D40"
			icon={I.EventSeat}
			src="https://actions.google.com/sounds/v1/ambiences/highway_near_waterfront.ogg"
		/>
		<AudioButton
			backgroundColor="#212121"
			icon={I.Games}
			src="https://actions.google.com/sounds/v1/ambiences/jungle_atmosphere_late_night.ogg"
		/>
		<AudioButton
			backgroundColor="#01579B"
			icon={I.Whatshot}
			src="https://actions.google.com/sounds/v1/ambiences/warm_afternoon_outdoors.ogg"
		/>
		<AudioButton
			backgroundColor="#33691E"
			icon={I.Opacity}
			src="https://actions.google.com/sounds/v1/animals/cat_purr.ogg"
		/>
		<AudioButton
			backgroundColor="#880E4F"
			icon={I.Nature}
			src="https://actions.google.com/sounds/v1/office/computer_typing_slow.ogg"
		/>
		<AudioButton
			backgroundColor="#311B92"
			icon={I.DoubleArrow}
			src="https://actions.google.com/sounds/v1/human_voices/summer_beach_ambience.ogg"
		/>
		<AudioButton
			backgroundColor="#F57F17"
			icon={I.LocalAirport}
			src="https://actions.google.com/sounds/v1/water/waves_crashing_on_rock_beach.ogg"
		/>
		<AudioButton
			backgroundColor="#006064"
			icon={I.Terrain}
			src="https://actions.google.com/sounds/v1/ambiences/fire.ogg"
		/>
		<AudioButton
			backgroundColor="#1A237E"
			icon={I.LocalDrink}
			src="https://actions.google.com/sounds/v1/ambiences/crickets_with_distant_traffic.ogg"
		/>
		<AudioButton
			backgroundColor="#311B92"
			icon={I.LocalAirport}
			src="https://actions.google.com/sounds/v1/transportation/windshield_wipers_no_water.ogg"
		/>
		<AudioButton
			backgroundColor="#F57F17"
			icon={I.Backspace}
			src="https://actions.google.com/sounds/v1/transportation/truck_drive.ogg"
		/>
		<AudioButton
			backgroundColor="#01579B"
			icon={I.Bathtub}
			src="https://actions.google.com/sounds/v1/transportation/suburban_streets_summer.ogg"
		/>
		<AudioButton
			backgroundColor="#b71c1c"
			icon={I.BeachAccess}
			src="https://actions.google.com/sounds/v1/household/long_silence_at_top.ogg"
		/>
		<AudioButton
			backgroundColor="#880E4F"
			icon={I.BlurLinear}
			src="https://actions.google.com/sounds/v1/household/wood_scraps_shuffling.ogg"
		/>
		<AudioButton
			backgroundColor="#BF360C"
			icon={I.ChangeHistory}
			src="https://actions.google.com/sounds/v1/foley/footsteps_on_fallen_leaves.ogg"
		/>
		<AudioButton
			backgroundColor="#1B5E20"
			icon={I.Cake}
			src="https://actions.google.com/sounds/v1/foley/metal_rattling_rhythmically.ogg"
		/>
		<AudioButton
			backgroundColor="#3E2723"
			icon={I.ConfirmationNumber}
			src="https://actions.google.com/sounds/v1/foley/objects_in_plastic_bottle.ogg"
		/>
		<AudioButton
			backgroundColor="#263238"
			icon={I.Brush}
			src="https://actions.google.com/sounds/v1/foley/slide_on_gravel_series.ogg"
		/>
	</Box>
)

export default Audioplayer
